<?php
/* talkgroup / number alias database */
$tgdb_array = [
    '0'			=> 'IDLE',
    '20'		=> '<small>TG20</small> DJSpot Test',
    '27'                => '<small>TG27</small> Local only DO0HWI',
    '28'                => '<small>TG28</small> Local only DO0RDG',
    '8'                 => '<small>TG8</small> Local Quasselstrippe',
    '77'		=> '<small>TG77</small> Sysop Talk only',
    '80'                => '<small>TG80 Mecklenburg Vorpommern</small',    
    '81'                => '<small>TG81</small> Berlin Brandenburg',
    '82'                => '<small>TG82</small>',
    '83'                => '<small>TG83</small>',
    '84'                => '<small>TG84</small> NRW',
    '85'                => '<small>TG85</small>',
    '86'                => '<small>TG86</small>',
    '87'                => '<small>TG87</small>',
    '88'                => '<small>TG88</small> Bayern',
    '89'                => '<small>TG89</small> Thüringen',
    '91'		=> '<small>TG91</small> TG Worldwide',
    '92'		=> '<small>TG92</small> TG Europa',
    '99'                => '<small>TG99</small> Weimar',
    '232'               => '<small>TG232</small> Austria',
    '2327'              => '<small>TG2327</small> OE Tirol',
    '262'               => '<small>TG262 DL</small> Link-Verbund',
    '264'		=> '<small>TG264</small> Interlink DL1BH',
    '666'		=> '<small>TG666</small> Jens`s VIP Lounge',
    '2621'              => '<small> Berlin Brandenburg <br> Link-Verbund</small>',
    '2622'              => '<small>TG2622</small> Hamburg / SH',
    '2629'              => '<small>TG2629  Thüringen / Sachsen Linkverbund</small>',
    '777'               => '<small>TG777</small> MultiRegioLink',
    '882'		=> '<small>TG882</small> Region München',
    '888'		=> '<small>TG888</small> Oberbayern',
    '985'		=> '<small>TG985</small> Lokal Suhl',
    '986'		=> '<small>TG986</small> Lokal Meiningen',
    '4711'		=> '<small>TG4711</small> echter Klön Talk',
    '7777'		=> '<small>TG7777</small> Sysop Talk only',
    '26298'		=> '<small>TG26298</small> Tetra Interlink',
    '26390'		=> '<small>TG26390</small> Region Neumarkt',
    '26284'		=> '<small>TG26284</small> Region Franken',
    '31868'             => '<small>TG31868</small> Weserbergland',
    '34497'             => '<small>TG34497 Korbach / Goldhausen </small>',
    '37574'             => '<small>TG37574 Local Bierstadt Einbeck </small>',
    '56479'		=> '<small>TG56479</small> Region Westerwald',
    '9999'              => '<small>TG9999</small> Papagai',
    'TG262_Holstein'    => 'Elbe Relais Verbund'
];

?>
